# Generated by Django 6.0.3 on 2026-03-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='image_hash',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
